FROM node:20-alpine
RUN apk add curl

WORKDIR /opt/web

COPY package.json package-lock.json .
RUN npm ci

COPY . .
RUN npx @11ty/eleventy

EXPOSE 3000
CMD ["npx", "http-server", "-p", "3000", "-a", "0.0.0.0", "./_site"]
